### ISSUE TITLE
 504 Deadline Exceeded

### ISSUE THREAD

**Issue by QuangLe1997** [googleapis/python-pubsub#1210]
i have code
``` python
from google.cloud import pubsub_v1

if __name__ == '__main__':
    publisher = pubsub_v1.PublisherClient(
        credentials="/Users/quang/.config/gcloud/application_default_credentials.json"
    )
    a = publisher.list_topics(
        timeout=10,
    )
    print(a)
```
it raise error
 in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded

**Comment by mukund-ananthu** [comment]
In the code, you are attempting to list the topics, without specifying which project you want to list the topics in, which won't work. Refer https://cloud.google.com/pubsub/docs/samples/pubsub-list-topics#code-sample for the public documentation for listing topics using the Python client library. 

Closing this since this is not an issue with the client library.
