### ISSUE TITLE
Implement new client options

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-pubsub#166]
Add support for the three new client_options `quota_project_id`, `scopes`, and `credentials_file`.  These options are implemented on the mirogenerator, so the completion of the migration may automatically fulfill this.

https://googleapis.dev/python/google-api-core/latest/client_options.html

**Comment by meredithslota** [comment]
@plamut is working on the microgenerator pieces so assigning to him to look into.

**Comment by plamut** [comment]
Hmm... looking at the [code](https://github.com/googleapis/python-pubsub/blob/b1bfc9e7ae540fed4a5ae81f9d895072a255a15d/google/cloud/pubsub_v1/publisher/client.py#L143-L151), the publisher client does not even pass `client_options` to the underlying GAPIC client, because it takes them out of `kwargs` and never puts them back (`kwargs` are passed to the GAPIC client). The only thing used is `target` passed to the created GRPC channel a few lines below.

We need to fix that by keeping `client_options` in `kwargs` (both in publisher and subscriber), but other than that the new options should be supported out of the box after we migrate to microgenerator.
