### ISSUE TITLE
Remove six dependency

### ISSUE THREAD

**Issue by HemangChothani** [googleapis/python-pubsub#181]
As `google-cloud-pubsub` library has dropped the support of `Python2.7`, is it ok to remove the dependency of `six` library?

cc:// @pradn @plamut

**Comment by plamut** [comment]
@HemangChothani The support has not been dropped (just) yet, we still need to make a release. :)

Since it's quite big a change, let's wait with any non-necessary changes to minimize the risk of something going wrong. Of course, once we are confident that the new major version works well, we can start cleaning up Python 2 stuff.

**Comment by meredithslota** [comment]
@kamalaboulhosn to weigh in here.

**Comment by plamut** [comment]
With the Python 2.7 support dropped, we indeed don't need `six` anymore in the 2.x versions, we can unblock this.

However, depending on the number of changes required, it might be better to do this task gradually if the the resulting cleanup PR turns out to be too large. Some caution is advised, even though the test coverage is decent.

**Comment by plamut** [comment]
I found some free capacity to resolve this for good, will start working on it.
