### ISSUE TITLE
Please consider dropping `request` parameter

### ISSUE THREAD

**Issue by rvandegrift** [googleapis/python-pubsub#205]
After using the new v2 client for a few days, I'm perplexed by the `request` parameter.  I could be missing something, but I think it should be removed entirely.

Here's my reasoning:

1. It looks like all functions where I could call `f({'param': 'value'})` I can also call `f(param='value')`.  The second is more idiomatic python and requires less punctuation.

1. In all cases that I've seen so far, it could always be replaced by keyword-arguments: if a consumer only has a `dict` with the parameters, we can always write `publisher.list_topics(**params)`.  That's also more idiomatic python with less unnecessary punctuation.

1. Making `request` a positional parameter has created hard to troubleshoot error messages.  Code with `<2.0.0` style positional arguments now cause a perplexing exception about `request`.  It took quite a lot of digging to figure out what I was supposed to do.  I don't think I'm the only one, there already been two github issues about it (#182, #194).  If all arguments were keyword-only, then python would raise a much more helpful TypeError about providing an incorrect number of positional arguments.  And if the error messages were that clear, I'm not sure the conversion utility would be required: there's lot of prior art for keyword-only args in Google python libraries.  That switch would've been quite natural.

The third item would be improved if `request` were made a keyword-only arg like the rest.  But given the first two, I don't see why it's worth having at all.

**Comment by plamut** [comment]
@busunkim96 You probably know better what the rationale was to add `request` parameter to the generated methods? Easier future extensibility without breaking user code?

**Comment by busunkim96** [comment]
Hi @rvandegrift,

Thanks for taking the time to  file an issue and provide feedback.

First, a little bit of context about the libraries and the motivation for changing method calls: 

Most of the `google-cloud-*` libraries are generated from `.proto` files which define the API. You can see the Pub/Sub ones [here](https://github.com/googleapis/googleapis/tree/master/google/pubsub/v1).   At the API level, making a required argument an optional argument is not a breaking change. For example, if Pub/Sub has method `foo` with required arguments `a, b, c` making `b` optional and keeping `a, c` required is non-breaking.

Previously we mapped required API arguments to positionals and optional arguments to kwargs. This meant that a non-breaking API change could result in a breaking Python library change.

e.g. `def foo(a, b, c)` ==> `def foo(a, c, b=None)` would break existing method call `foo("a", "b", "c")`.

For the new surface one of our highest priorities was making sure non-breaking API changes would never result in breaking Python library changes.

---

> 1. It looks like all functions where I could call f({'param': 'value'}) I can also call f(param='value'). The second is more idiomatic python and requires less punctuation.
>
> 2. In all cases that I've seen so far, it could always be replaced by keyword-arguments: if a consumer only has a dict with the parameters, we can always write publisher.list_topics(**params). That's also more idiomatic python with less unnecessary punctuation.

It looks like in Pub/Sub, all the request attributes are always available on the method as kwargs. This isn't the case for every API. In AutoML, some optional request attributes are only accessible on the `request` object. The request args that get elevated to the method signature are decided by the `google.api.method_signature` proto annotation. See https://google.aip.dev/client-libraries/4232

In AutoML, `ListDatasets` only has one flattened parameter `parent`.
```proto
  rpc ListDatasets(ListDatasetsRequest) returns (ListDatasetsResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=projects/*/locations/*}/datasets"
    };
    option (google.api.method_signature) = "parent";
  }

// Request message for [AutoMl.ListDatasets][google.cloud.automl.v1.AutoMl.ListDatasets].
message ListDatasetsRequest {
  // Required. The resource name of the project from which to list datasets.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "locations.googleapis.com/Location"
    }
  ];

  // An expression for filtering the results of the request.
  //
  //   * `dataset_metadata` - for existence of the case (e.g.
  //             image_classification_dataset_metadata:*). Some examples of using the filter are:
  //
  //   * `translation_dataset_metadata:*` --> The dataset has
  //                                          translation_dataset_metadata.
  string filter = 3;

  // Requested page size. Server may return fewer results than requested.
  // If unspecified, server will pick a default size.
  int32 page_size = 4;

  // A token identifying a page of results for the server to return
  // Typically obtained via
  // [ListDatasetsResponse.next_page_token][google.cloud.automl.v1.ListDatasetsResponse.next_page_token] of the previous
  // [AutoMl.ListDatasets][google.cloud.automl.v1.AutoMl.ListDatasets] call.
  string page_token = 6;
}
```

This results in the Python function definition for `list_datasets` only having `parent` as a kwarg.  If I want to use `filter`, `page_size`, or `page_token`, I have to construct a request object.

```py
    def list_datasets(
        self,
        request: service.ListDatasetsRequest = None,
        *,
        parent: str = None,
        retry: retries.Retry = gapic_v1.method.DEFAULT,
        timeout: float = None,
        metadata: Sequence[Tuple[str, str]] = (),
    ) -> pagers.ListDatasetsPager:
 ```

Sample code:
```py
from google.cloud import automl_v1beta1 as automl

client = automl.AutoMlClient()

# A resource that represents Google Cloud Platform location.
project_location = f"projects/{project_id}/locations/{compute_region}"

# List all the datasets available in the region by applying filter.
request = automl.ListDatasetsRequest(parent=project_location, filter=filter_)
response = client.list_datasets(request=request)
```
---
> Making request a positional parameter has created hard to troubleshoot error messages. Code with <2.0.0 style positional arguments now cause a perplexing exception about request. It took quite a lot of digging to figure out what I was supposed to do. I don't think I'm the only one, there already been two github issues about it (#182, #194). If all arguments were keyword-only, then python would raise a much more helpful TypeError about providing an incorrect number of positional arguments. And if the error messages were that clear, I'm not sure the conversion utility would be required: there's lot of prior art for keyword-only args in Google python libraries. That switch would've been quite natural.

This is a fair point. My guess is that it is positional to signal that is is "required" (even though it is optional if the service owners have provided a method overload via `google.api.method_signature` 😄 ). I'd be hesitant to change the signature at this point though, since it would be another breaking change.

---

@software-dov Could you take a look to make sure I haven't misrepresented anything here?

**Comment by software-dov** [comment]
@busunkim96 This entire reply is spot on.

> one of our highest priorities was making sure non-breaking API changes would never result in breaking Python library changes.

This in particular is responsible for the new method semantics. The old semantics violate this priority, but the fact that Python is a dynamic language with no built-in mechanism for function overloading or type-based dispatch (plus the flexibility of passing in list/dict representations which completely elides more nuanced type information) leaves us with not a lot of great options for making a new general method signature rule.

In an ideal world, there would be one method variant per method signature annotation plus one variant that just takes a request. We felt the best compromise between flexibility and user ergonomics was to make the `request` parameter optional and not keyword-only, indicating that it was special, and making the superset of all the flattened parameters in all the method signature annotations into keyword-only args.

I agree, making `request` a keyword-only arg would have solved this particular problem, but at the cost of making the method signature more convoluted and less clear. In the end, even if we had made `request` keyword only as well, this is a change that requires clear, explicit documentation in UPGRADING.md files, method docstrings, and API samples, and we could do better there.

Changing the semantics now would constitute yet another breaking change, and I don't think we can force that on the users of all the client libraries at the moment.

**Comment by rvandegrift** [comment]
@busunkim96 @software-dov - thanks for the explanation, I guess I got lucky just looking at pubsub.

I'm glad that avoiding breakage in python is a priority here - we've had the previous client break due to backwards-compatible changes in the pubsub API.  So thanks, I appreciate that greatly!

**Comment by plamut** [comment]
Since the question has been answered and since the `request` parameter will not be dropped, the ticket can be closed  - but feel free to reopen it, if the discussion hasn't covered everything.
