### ISSUE TITLE
PubSub: easier way to acknowledge a message using ack_id

### ISSUE THREAD

**Issue by guyandtheworld** [googleapis/python-pubsub#28]
I was going through the PubSub pull docs [here][1]

```
from google.cloud import pubsub_v1

# TODO project_id = "Your Google Cloud Project ID"
# TODO subscription_name = "Your Pub/Sub subscription name"
# TODO timeout = 5.0  # "How long the subscriber should listen for
# messages in seconds"

subscriber = pubsub_v1.SubscriberClient()
# The `subscription_path` method creates a fully qualified identifier
# in the form `projects/{project_id}/subscriptions/{subscription_name}`
subscription_path = subscriber.subscription_path(
    project_id, subscription_name
)

def callback(message):
    print("Received message: {}".format(message))
    message.ack()

streaming_pull_future = subscriber.subscribe(
    subscription_path, callback=callback
)
print("Listening for messages on {}..\n".format(subscription_path))

# result() in a future will block indefinitely if `timeout` is not set,
# unless an exception is encountered first.
try:
    streaming_pull_future.result(timeout=timeout)
except:  # noqa
    streaming_pull_future.cancel()
```

In the above example, the message is ack-ed as soon as it is received. But I want to acknowledge only when my local celery workers finish processing the message so that PubSub can redeliver the message if the worker fails. So I take the ack_id of the message and pass it onto the worker.

    params["ack_id"] = message._ack_id
    start_aggregation.delay(params)

 
I couldn't find a convenient way to ack a message using the ack_id. Does PubSub python have a method to do that? I could only find [this][2].

  [1]: https://cloud.google.com/pubsub/docs/pull
  [2]: https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/acknowledge?apix_params=%7B%22subscription%22%3A%22projects%2Falrt-ai%2Fsubscriptions%2Fnews_aggregator%22%2C%22resource%22%3A%7B%22ackIds%22%3A%5B%22CypYEU4EISE-MD5FU0RQBhYsXUZIUTcZCGhRDk9eIz81IChFEAEgbwstQloeYmhcXHUHUAoZcHhpdWwPE1IIRVl-d2s5MmFbWHAGUg8Zcnpic2taEin4mIDUpKL2PHJgZIDX4s8sUpCNmsxoZh89WxJLLD5-LThFQV5AEkwmDURJUytD%22%5D%7D%7D

**Comment by kamalaboulhosn** [comment]
It is intentional that one cannot ack via the `ack_id`. It is necessary to call `message.ack()` to acknowledge the message. If you were to ack with the ack ID directly, then the flow control mechanism in the client library would not realize that the message has been acknowledged, resulting in message delivery stopping once the flow control limit is reached. 

It seems as though using celery workers should be unnecessary with Pub/Sub. You are basically putting a queue of work in front of a Pub/Sub queue, which seems like a double-queueing. In order to get around the GIL and single thread at a time limitations, one can either start up subscribers in different processes, which will load balance across the subscribers, or replace the [Scheduler](https://googleapis.dev/python/pubsub/latest/subscriber/api/scheduler.html) with a process-based scheduler instead of a thread-based scheduler.

**Comment by guyandtheworld** [comment]
@kamalaboulhosn Great insight! So the thing was, before PubSub, we used a flask API to add the tasks to the RabbitMQ queue, which would be processed by celery. Now we switched to PubSub, this sounds like a way more convenient way to do it. Thanks a lot for your help. Closing this issue.
