### ISSUE TITLE
"Too many open files" while subscribing to ~100 subscriptions

### ISSUE THREAD

**Issue by gastlich** [googleapis/python-pubsub#287]
Hi there!

We've got a case in production in which we would like to consume 100+ subscriptions.
In most cases no messages are consumed at all with no log messages.
If we save `stdout` to a file we sometimes get error messages reporting "Too many open files".

We have tried using both custom `FlowControl` and `ThreadScheduler`, but we haven't noticed any positive impact on our case.

Is it possible to asynchronously subscribe to 100+ subscriptions?

#### Environment details

  - OS type and version: Mac OS X 10.14.6 and Debian GNU/Linux 9 (stretch)
  - Python version: Python 3.7.9
  - pip version: 20.2.4
```
cachetools==4.2.1; python_version ~= '3.5'
certifi==2020.12.5
chardet==4.0.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'
google-api-core[grpc]==1.26.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'
google-auth==1.25.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'
google-cloud-pubsub==2.3.0
googleapis-common-protos[grpc]==1.52.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'
grpc-google-iam-v1==0.12.3
grpcio==1.35.0
idna==2.10; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'
libcst==0.3.17; python_version >= '3.6'
mypy-extensions==0.4.3
packaging==20.9; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'
proto-plus==1.13.0; python_version >= '3.6'
protobuf==3.14.0
pyasn1-modules==0.2.8
pyasn1==0.4.8
pyparsing==2.4.7; python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2, 3.3'
pytz==2021.1
pyyaml==5.4.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'
requests==2.25.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'
rsa==4.7; python_version >= '3.6'
six==1.15.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'
typing-extensions==3.7.4.3
typing-inspect==0.6.0
urllib3==1.26.3; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' and python_version < '4'
```

#### Steps to reproduce

  1. Create 100+ subscriptions in GCP with default settings
  2. Populate subscriptions with thousands of messages containing just `{}` payload
  3. Based on the included code example, fill list of `SUBSCRIPTIONS` with your newly created subscriptions
  4. Start the python snippet
  5. In most cases nothing logged to `stdout`

#### Code example

```python
import time

from google.cloud import pubsub_v1

SUBSCRIPTIONS = [
    # list of 100+ subscriptions
]


def ack_message(message):
    message.ack()
    print(message)


if __name__ == "__main__":
    subscriber = pubsub_v1.SubscriberClient()

    for subscription in SUBSCRIPTIONS:
        subscriber.subscribe(
            subscription,
            callback=ack_message,
        )

    while True:
        time.sleep(60)
```

#### Stack trace
```
E0209 16:50:30.682336000 123147221856256 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
E0209 16:50:30.682452000 123147221856256 ev_poll_posix.cc:945]         pollset_work: {"created":"@1612889430.682425000","description":"Too many open files","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0209 16:50:30.682478000 123147221856256 completion_queue.cc:1065]     Completion queue next failed: {"created":"@1612889430.682425000","description":"Too many open files","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
```

**Comment by plamut** [comment]
@gastlich 

> Is it possible to asynchronously subscribe to 100+ subscriptions?

It should be, provided that the machine running the subscriber is fast enough to actually benefit from that. Simultaneously streaming messages from 100+ subscriptions does sound quite a lot, but it depends on the message load of course.

The thing here is that each `subscriber.subscribe()` call starts streaming the messages from a particular subscription in the background, and each stream consumes system resources. It appears that all these streams collectively try to open too many files (pipes, in particular), hitting the system's limits.

What's the output of `ulimit -Sn`? On my machine it's 1024.

Assuming there are no resource leaks and the total number of files that are expected to be created is bounded, it might help to increase the allowed number of open files before running the app, e.g.:
```
$ ulimit -n 4096
```

While the app is running, it might also be worth checking how many files are open by python, just get an idea what's happening:
```
$ lsof  | grep python | wc -l
```

Does that help with your problem?

**Comment by gastlich** [comment]
@plamut 
Thank you for your reply and the insights.

I have check the limits suggested by you. On production we've got this limit set to:
```
$ ulimit -Sn
1048576
```
Locally, I had indeed this limit set to just:
```
$ ulimit -Sn
256
```
After, changing the value to **4096** I haven't reproduced the "Too many open files" issue, but it didn't allow me to consume 100+ subscriptions. If this was the case, it would be working fine on production, since the limit is very high.

I compared `DEBUG` logged messages from `google.cloud.pubsub_v1` between working example (around 80 subscriptions) and not working (100+ subscriptions).

Please find the log files attached:
1. Logs from working example: [working_80_subscriptions.log](https://github.com/googleapis/python-pubsub/files/5958091/working_80_subscriptions.log)
2. Logs from **NOT** working example: [not_working_100_subscriptions.log](https://github.com/googleapis/python-pubsub/files/5958092/not_working_100_subscriptions.log)

As you can see in the later example, the subscribers never consume any of the messages (no `Consumed` message logged) and they are hanging forever around lease management

```
DEBUG:google.cloud.pubsub_v1.subscriber._protocol.leaser:Snoozing lease management for 8.829326 seconds.
DEBUG:google.cloud.pubsub_v1.subscriber._protocol.leaser:The current deadline value is 10 seconds.
DEBUG:google.cloud.pubsub_v1.subscriber._protocol.leaser:Snoozing lease management for 8.853522 seconds.
DEBUG:google.cloud.pubsub_v1.subscriber._protocol.leaser:The current deadline value is 10 seconds.
DEBUG:google.cloud.pubsub_v1.subscriber._protocol.leaser:Snoozing lease management for 0.648498 seconds.
DEBUG:google.cloud.pubsub_v1.subscriber._protocol.leaser:The current deadline value is 10 seconds.
DEBUG:google.cloud.pubsub_v1.subscriber._protocol.leaser:Snoozing lease management for 3.678817 seconds.
DEBUG:google.cloud.pubsub_v1.subscriber._protocol.leaser:The current deadline value is 10 seconds.
DEBUG:google.cloud.pubsub_v1.subscriber._protocol.leaser:Snoozing lease management for 5.258003 seconds.
```

I thought maybe changing `max_lease_duration` should help, but no luck from side.

**Comment by plamut** [comment]
@gastlich Thanks for the logs.

Just as a sanity check, can you confirm that the working example had enough messages in each subscription too keep the streams busy? Asking because in the `working_80` log I see 96 occurrences of streams being created:
```
Started helper thread Thread-ConsumeBidirectionalStream
```
On the other hand, there are only 57 occurrences of `streaming_pull_manager:Processing` in the same log, meaning that some of the subscribers were idling.

Comparing this to the `not_working_100` log, there were 110 streams created and 100 batches of received messages, but for some reason these messages were never dispatched to the `ack_message()` callback. There were also no `Sent request(s) over unary RPC` entries, meaning that the client did not send anything back to the server (e.g. MODACK requests).

In any case, it appears that after a certain (soft?) threshold things get stuck. If I have to guess, it's probably because too many threads get created and weird things start happening.

> I thought maybe changing `max_lease_duration` should help, but no luck from my side.

That's kind of expected, since the setting only affects the lease management. If messages are not being processed and are not ACK-ed (or explicitly NACK-ed), they will eventually expire in any case.

BTW, for debugging I usually use the following log config that includes the timestamps and thread names, if it helps in any way.
```py
log_format = (
    "%(levelname)-8s [%(asctime)s] %(threadName)-33s "
    "[%(name)s] [%(filename)s:%(lineno)d][%(funcName)s] %(message)s"
)

logging.basicConfig(level=logging.DEBUG, format=log_format)
```

If I understood correctly, custom `FlowControl` settings did not help? (e.g. reducing `max_messages` and max_bytes` to decrease the load)

If so, the only quick workaround that I can think of now is to perhaps run the code example in a few separate processes with each subscribing only to a moderate subset of all subscriptions? The total number of threads will still be quite large, but at least fewer of them will be competing for the same GIL.

**Comment by gastlich** [comment]
@plamut Thanks for your message. I will be confirming your suggestions shortly, just wanted to let you know, that after leaving **NOT_working_example** for a while, it started to consume messages after around 23 minutes.

Whereas the working example starts within seconds. I will come back to you with the details later today. (Once I've grab enough logs).

Regarding FlowControl, I've tried setting very low `max_messages` and `max_bytes` limits with extened `max_lease_duration `, but it didn't work. The number in the logs saying "The current deadline value is 10 seconds." didn't change to reflect `max_lease_duration`, but I'm not sure if it supposed to change or not.

**Comment by plamut** [comment]
@gastlich Whoa, there must have been some serious contention initially before the things got running. Thought - is the behavior the same if subscriptions are started with some delay between each other? (a short `time.sleep()` in the `for` loop).

Thanks for your willingness to conduct additional tests on your own, looking forward to the findings!

> The number in the logs saying "The current deadline value is 10 seconds." didn't change to reflect max_lease_duration, but I'm not sure if it supposed to change or not.

Ah, that number is actually the current ACK deadline for the messages and it is dynamically adjusted by the lease manager based to the 99th percentile of observed message ACK times (up to some upper limit). The ACK deadline repeatedly gets extended until a message is either ACK-ed or NACK-ed, or the `max_lease_duration` deadline is hit.

Initially, the ACK deadline is set to 10 seconds (the server-side default) and that number is used when extending the deadline.
Once enough ACK data has been collected, that number is adjusted to the 99th percentile of observed message ACK times. If there have been no ACKs, however, there's no data to collect and the initial value of 10 seconds is used. The logs appear normal in this respect.

I hope this makes more sense now?

**Comment by gastlich** [comment]
@plamut 
Yes, it makes sense now. I've read about extending ACK deadline before.

I've finished collecting logs with your log format. Please find them attached here:
[formatted.log](https://github.com/googleapis/python-pubsub/files/5959523/formatted.log)

I made sure all subscriptions have at least 10k of very small messages.

First of all, I would like to point out, it took once again almost exactly 30 minutes to start consuming messages (without few seconds). This looks suspicious. Are you aware of any timeouts/deadlines, which could be potential culprits?

Secondly, it looks like after consuming 3653 messages it entered once again this pattern of lease snoozing (I kept it running for a bit longer than 30 minutes, to check if consumption stays smooth).

Lastly, I tried delaying creation of new subscriptions for 1 second. It looks like it subscribed (and started to consume) nicely to the first 101 subscriptions and then exactly 30 minutes later subscribed to the remaining 9. If you were interested in that log file also, I can find a way to share it publicly.

Thanks for you help in advance.

**Comment by plamut** [comment]
@gastlich Sounds good, and the "almost exactly 30 minutes" timeout could be useful.

From what I was told this is likely the maximum amount of time the server will allow a streaming RPC to be open. The stream then terminates and the client re-establishes it.

The limit of ~100 subscriptions is also interesting - it _might_ be the maximum number of simultaneous connections allowed by the gRPC layer (all streams use the same client here)... or something on the backend, I see some 500 RST_STREAM error in the logs, which has been observed in quite a few unrelated places (including languages other that Python and services other than PubSub).

My theory - there is some limit after which starting additional streams just breaks things up. Then, after 30 minutes, some of the streams get terminated and the rest of the streams can start pulling the messages. Once the disconnected streams re-connect, things get stuck again.

Delaying the initial stream creation seems to support this - it works fine initially, but then the underlying channel (?) gets congested and the client cannot send any requests back. And it stops pulling the messages, because it has accumulated too many messages internally and hits the flow control limits.

---

Is it necessary that all subscriptions run with the same client instance/process/machine? Could the load in your app be evenly distributed among independent subscribers or would that be too complicated?

Saying this, because ATM it does not seem like something that could be quickly fixed in the short term, I'm afraid.

**Comment by gastlich** [comment]
thanks @plamut for the further investigation. I think your suggestion about splitting subscriptions into smaller batches and running independent subscribers in unique processes should work. We haven't tried it yet though. This is going to be our rescue plan.

Currently, instead of subscribing to all subscriptions (around 140), we manually hand-picked 80 of them, which were the most important to us and we made sure we are not even close to the magical 100 subscribers :)

If at any time we get closer, we are going to try splitting the subscriptions instead of in the worst case maybe moving to cloud functions?

Thanks for your all feedback and support. I think this issue might be closed now :)

**Comment by plamut** [comment]
@gastlich Depending on the load, it might even work to use more than a single subscriber instance (just instantiate the class multiple times) so that each underlying transport channel does not have to deal with 100+ simultaneous streams - the cloud frontend only allows ~100 streams per connection, which is consistent with your observations (e.g. 101 subscriptions working with remaining 9 put on hold).

If that doesn't work, you can also try with multiple independent processes, although at some point the app can start hitting the limits of what a single instance is capable of, in which case multiple instances should probably be considered.

There was also a remark about possibly refactoring the subscriptions (read: reducing their count) to distribute the load differently, but that's of course entirely use-case dependent, and it might not even be feasible at all.

Good luck with the project and feel free to re-open the issue should you have any more questions!
