### ISSUE TITLE
Make publish futures compatible with `concurrent.futures.as_completed()`

### ISSUE THREAD

**Issue by mbrancato** [googleapis/python-pubsub#368]
#### Environment details

  - OS type and version: Linux
  - Python version: `Python 3.7.7`
  - pip version: `pip 21.0.1`
  - `google-cloud-pubsub` version: 
```Name: google-cloud-pubsub
Version: 2.3.0
Summary: Google Cloud Pub/Sub API client library
Home-page: https://github.com/googleapis/python-pubsub
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/mike/.pyenv/versions/3.8.6/envs/detection-processor/lib/python3.8/site-packages
Requires: grpc-google-iam-v1, proto-plus, google-api-core, libcst
Required-by: 
```

#### Steps to reproduce

  1. Create multiple publish futures with `publisher.publish()`
  2. Use `in concurrent.futures.as_completed()` as a generator to trigger on completion.

#### Code example

```python
future_list = []

for msg in messages:
    future_list.append(publisher.publish(topic_path, msg))

for _ in concurrent.futures.as_completed(
    fs=future_list,
):
    # Do something
    continue
```

#### Stack trace
```
'Future' object has no attribute '_condition'
```

I understand that the publish future is not REALLY a concurrent future object. This attribute error does not happen with all messages, it's a minority of messages. I'm not sure what causes some publish futures to work with `as_completed` and some do not.

**Comment by plamut** [comment]
@mbrancato  I can't say for sure, would have to investigate. It's an interesting finding, though, thanks for bringing this up!

**Comment by mbrancato** [comment]
Thanks @plamut - I the output as I left some of my custom messaging around the output.

If I can figure out what types of messages cause this, I'll let you know.

**Comment by plamut** [comment]
@mbrancato That would be great, was just about to ask if you observed any patterns when a future can(not) be used. Maybe when an error happens behind the scenes, but a happy case works just fine?

**Comment by mbrancato** [comment]
@plamut - I think I understand what is happening. I think it happens because I call it like this:

```python
concurrent.futures.as_completed(fs=future_list, timeout=10)
```

And when I look at the code for `as_completed` creates a `set()` from the list of futures. And then it tries to yield compelted futures:

https://github.com/python/cpython/blob/bf2e7e55d7306b1e2fce7dce767e8df5ff42cf1c/Lib/concurrent/futures/_base.py#L232

From there, it pops items off the set when completed:
https://github.com/python/cpython/blob/bf2e7e55d7306b1e2fce7dce767e8df5ff42cf1c/Lib/concurrent/futures/_base.py#L198

I think if the timeout is hit, it gets to this `finally` block:

https://github.com/python/cpython/blob/bf2e7e55d7306b1e2fce7dce767e8df5ff42cf1c/Lib/concurrent/futures/_base.py#L257-L261


There's no check there for the `_condition` attribute so it raises an error. This obviously isn't in the Google Pubsub library code, but I think the futures implemented by the library would need to implement this attribute for it to work.

**Comment by plamut** [comment]
@mbrancato Thanks for digging in and saving some time on our side. :)

It appears to me that `finally` block is executed because an [exception happens](https://github.com/python/cpython/blob/bf2e7e55d7306b1e2fce7dce767e8df5ff42cf1c/Lib/concurrent/futures/_base.py#L194) in `_yield_finished_futures()`, as publish futures have no `_condition` attribute (and then an error happens again in the `finally` block).

A concern here is that `concurrent.futures.as_completed()` uses some attributes of `concurrent.futures.Future` which should be considered implementation details. If publish futures tried to mimick those, they could break if `concurent.futures` implementation changes.

But if I understand correctly, you would simply need a function similar to `concurrent.futures.as_completed()` that yields futures from the given iterable as they complete?

If that's the case, the library could provide it's own helper method to support that. I'll clasify this as a feature request and put it up for consideration.

BTW, is there any other specific behavior you would like to see in the helper besides timeouts?

**Comment by mbrancato** [comment]
Thanks @plamut . I think implementing a timeout and support for an Iterable of Futures as the native function does would be best.

**Comment by plamut** [comment]
@mbrancato I have an update, in principle the proposal has been given a green light.

We still need to discuss where exactly to place the new helper (either here or maybe in `api-core` to be used by other libs, too), but it seems likely to appear in one of the releases in Q2.
