### ISSUE TITLE
Doc to explain the internals of library.

### ISSUE THREAD

**Issue by sp1rs** [googleapis/python-pubsub#440]
Is there any doc to explain the internals of the library? For ex: `Dispatcher` , `bidi BackgroundConsumer` , `Leaser`, `HeartBeater` etc.

**Comment by plamut** [comment]
@sp1rs These are all internal classes used for the streaming pull and managing different aspects related to it. In principle users should not be concerned about them, especially because they can always change without notice (e.g. due to refactoring, there have been some internal discussion about it in the past).

I'd say it's unlikely comprehensive docs will be written about the internal implementation details, but we could still help if you have some specific questions?

**Comment by sp1rs** [comment]
I want to understand how stream pulling is done in the background. How many threads were created in the background? How the data is pulled from the subscription queue?

**Comment by plamut** [comment]
@sp1rs Streaming pulls are managed by an internal class `StreamingPullManager`. When invoking `subscriber.subscribe()`, a new streaming pull manager instance is created, and its [open()](https://github.com/googleapis/python-pubsub/blob/7345145f70e7508411d371bf67d1670bd9eac29a/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py#L496-L554) is called.

The manager creates four threads:
 - **Background consumer** - this establishes a message stream with the server, over which the client receives the messages from a subscription. Whenever a new batch of messages is received, the manager's [_on_response()](https://github.com/googleapis/python-pubsub/blob/7345145f70e7508411d371bf67d1670bd9eac29a/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py#L682-L740) callback is invoked.
 The stream can also be paused and resumed depending on the current message load (the client makes sure that not too many messages are accumulated in internal queues, otherwise the client could run out of memory in the worst case).
 - **Hearbeater** - this thread sends heartbeat requests to the server every 30 seconds to tell it that the client is still alive. Without that, the server would automatically terminate the stream after 60 seconds without hearing from the client.
 - **Leaser** - When a message is received, but not yet acknowledged, it is said to be "leased". Such message needs to be ACK-ed before the ACK deadline, otherwise it expires and the server re-sends it. However, sometimes processing a message takes longer, in which case the leaser thread automatically extends the ACK deadline to prevent it from expiring.
 The number and the size of the currently leased messages also represents the "load". If the load is too high, the client temporarily pauses the stream.
 - **Dispatcher** - It would be undesirable if sending requests such as ACK, MODACK, NACK blocked the execution. For this reason, the code making these requests just puts them in internal queue The _dispatcher_ then takes these requests from the queue and actually sends them to the server in the background.
 
Another thing worth mentioning is the **scheduler**. When a message is sent to the user-provided callback, it's done in the background through this scheduler. A message is [submitted](https://github.com/googleapis/python-pubsub/blob/7345145f70e7508411d371bf67d1670bd9eac29a/google/cloud/pubsub_v1/subscriber/scheduler.py#L107-L125) to an internal thread pool which dispatches it to the user callback, i.e. it runs the callback in a separate thread. The default thread pool is is created with 10 threads, meaning that 10 user callbacks can execute concurrently.

This is the high level overview of what happens in the background. For details on each specific operation, I suggest reading through the code, or maybe setting the logging level to DEBUG and observing what's happening in the background.

But as I mentioned, these are all implementation details, and it's unlikely that it it will be added to the docs, since after all, the library users should not be concerned by all this. It's the library's goal to make message streaming much more straightforward than it actually is.

**Comment by sp1rs** [comment]
@plamut Thank you so much for the great explanation. I think it would be great if this explanation can be part of the doc. It helps a lot. Again thank you so much for the explanation.

**Comment by tzoratto** [comment]
I second @sp1rs's point of view, especially for the "Leaser" part. In my opinion, about background consumer, heartbeater, dispatcher you're right @plamut these are implementation details that should not concern users. But when it comes to the leaser, the user **must** know what the library does internally, because depending on what the library handles by itself, the user will have to handle lease management in his own code or not.

Lease management is critical when message processing duration is not constant and cannot be considered as an implementation details, it should be documented so the user knows what are his responsibilities and what is already handled by the lib.

Thank you for your detailed explanation here anyway, it has been useful :+1:

**Comment by plamut** [comment]
@tzoratto Thanks for sharing your view, I can bring this docs request to attention again.

As for the leaser - the leaser will keep repeatedly extending the ACK deadlines of the leased (i.e. received but not yet processed) messages for as long as necessary until the maximum lease time is hit (2 hours or something like that? Would need to check). In other words, the client code does not have to worry about that as long as it processes messages before the max lease duration.

This is for streaming pull, of course. If an app uses a synchronous pull, it will need to perform its own lease management.

**Comment by iamkeyur** [comment]
@planut Is there any way to extend ack deadline beyond 600s? Currently, that 600s is the max value. I do not see any value or args in the library where it would allow us to extend that deadline automatically. I need to send `modify_ack_deadline` request to do that.

**Comment by plamut** [comment]
@iamkeyur With asynchronous (streaming) pull, this happens automatically in the background, thus there's no need to do that manually. In fact, some Pub/Sub clients don't even expose the `modify_ack_deadline method()` (the Go client, for instance).

Or are you talking about the synchronous pull?

Mind, however, that for various reasons library users are encouraged to use asynchronous (streaming) pull instead.

**Comment by iamkeyur** [comment]
Hello,

We use synchronous pull. However, one thing I have noticed is that sync pull doesn't receive messages immediately. 

We have 1000 VMs listening to the same subscription. Queue may have 1000+ messages still it would take lot more time to empty the queue because pull request (timeout is 1 second) would result with no messages. Is this ideal behavior? 

Does asynchronous pull avoids this issue? We also tried sync pull with more timeout but same issue.

**Comment by plamut** [comment]
@iamkeyur

Asynchronous (streaming) pull streams the messages from the server as they become available, avoiding the overhead of polling the server. If streaming with multiple subscribers from the same subscription, the messages are load-balanced between them.

> We use synchronous pull. However, one thing I have noticed is that sync pull doesn't receive messages immediately.

I don't have insight into server-side internals, but IIRC there's some internal logic when a published message actually becomes available to be pulled (due to queuing, batching...). In practice this means that sometimes a `pull()` call does not return anything or less than `max_messages` which is what you have observed?

I don't believe an increased timeout would really help here, as this is the request timeout (to not block indefinitely), and not the time to wait for the messages to become available. Even with a large timeout, if the server doesn't have any messages ready to deliver, it will just respond "soon" with an empty response, even if the request timeout is large.
