### ISSUE TITLE
Excessive out traffic due to auto modack

### ISSUE THREAD

**Issue by chwangaa** [googleapis/python-pubsub#613]
Hi

I observe that the outbound traffic is larger than the inbound traffic, and after some quick digging it seems most of them is due to modify_ack messages. I set the default modify_ack to be 1 minutes, and according to the stats the 99% ack latency is well within 1 sec.

After reading the source code I found this line: https://github.com/googleapis/python-pubsub/blob/2fb6e1533192ae81dceee5c71283169a0a85a015/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py#L965

It seems for each request the client will always send a mod_ack. May I ask why is this necessary please? I don't see this behaviour in the synchronous pull model,. Is this specific to python client? I also don't see it in the c++ client. 

Thank you

**Comment by pradn** [comment]
Yes, the library sends modacks as soon as it receives the messages. This is a convenience that lets the user callback take as much time as it needs to before acking the message. If this behavior didn't exist, the user code would only be able to take up to the subscription's ackDeadline, which is a max of 10 min. This problem exists for Pull and StreamingPull. With the library's auto-leasing behavior, a message can be leased past this limit because the automatic modacks will continue to keep extending the message's ack deadline.

We don't currently have a way to turn this off. If the modack bandwidth is a concern, please make manual sync Pull calls or set up a StreamingPull connection on your own.

The behavior is not unique to the Python library. We have it for every language except PHP, which doesn't maintain state in the library. The C++ library also has this behavior, see [here](https://github.com/googleapis/google-cloud-cpp/blob/b7054f271f435383dc10d0c764327c0b7461adf0/google/cloud/pubsub/subscriber_options.h#L111-L154).

**Comment by pradn** [comment]
Closing this issue. Please reach out if you have further questions.
