### ISSUE TITLE
pylint: Instance of 'SubscriberClient' has no 'subscription_path' member

### ISSUE THREAD

**Issue by dinvlad** [googleapis/python-pubsub#67]
#### Environment details

  - OS type and version: macOS Mojave 10.14.6
  - Python version: `python --version` 3.7.7
  - pip version: `pip --version` 20.0.2
  - `google-cloud-pubsub` version: `pip show google-cloud-pubsub` 1.4.2

#### Steps to reproduce

  1. Use the stock subscription example from https://github.com/googleapis/python-pubsub/blob/master/docs/subscriber/index.rst
  2. Running `pylint` on it results in:
```
E1101: Instance of 'SubscriberClient' has no 'subscription_path' member (no-member)
```

#### Code example

```py3
from google.cloud import pubsub
subscriber = pubsub.SubscriberClient()

sub_path = subscriber.subscription_path(PROJECT, SUBSCRIPTION)
```

#### Stack trace
N/A

**Comment by dinvlad** [comment]
Might be related to https://github.com/googleapis/python-vision/issues/6

**Comment by anguillanneuf** [comment]
@dinvlad Thanks for your question. 

`subscription_path` is defined in `cloud/pubsub_v1/gapic/subscriber_client.py`:
https://github.com/googleapis/python-pubsub/blob/21e761ee89a4c03e105dc9cddbab0a34be9a9fda/google/cloud/pubsub_v1/gapic/subscriber_client.py#L109-L116

This method is being added in `cloud/pubsub_v1/subscriber/client.py` via the decorator:
https://github.com/googleapis/python-pubsub/blob/21e761ee89a4c03e105dc9cddbab0a34be9a9fda/google/cloud/pubsub_v1/subscriber/client.py#L43-L44

You should be able to see the method if you run `dir(subscriber)`. Does this help?

**Comment by dinvlad** [comment]
I think the issue is the typings, not necessarily that the method is not there (as it is). So I'd like to re-open this if possible, since the way this method is wired currently makes it incompatible with `pylint`.

**Comment by dinvlad** [comment]
Specifically, unlike the `subscriber()` method, the `subscription_path()` method is not wired into https://github.com/googleapis/python-pubsub/blob/master/google/cloud/pubsub_v1/subscriber/client.py

**Comment by anguillanneuf** [comment]
@plamut @pradn FYI for Pub/Sub v2. 

@dinvlad We really should be compatible with `pylint` because of `pylint`'s widespread usage 😞But for Version 1 of our library, this is probably not going to happen as it doesn't affect the functionality of the library. We are currently designing v2  - compatibility with third party tools will make into our considerations. Thank you again for raising it.

**Comment by dinvlad** [comment]
I see, thank your explaining @anguillanneuf ! We'll keep this in mind.

**Comment by anguillanneuf** [comment]
No problem @dinvlad ! We use [`nox`](https://nox.thea.codes/en/stable/), which complies to `PEP8`, see the [Contributing Guide](https://github.com/googleapis/python-pubsub/blob/master/CONTRIBUTING.rst#coding-style).

**Comment by plamut** [comment]
@dinvlad The classes in `gapic/` directory are auto-generated based on the `.proto` definitions, including the `SubscriberClient` class, and there is a manual layer on top of that - the `Client` class from `subscriber/client.py`.

In order to avoid code duplication and to prevent the manual and generated client classes going out of sync, methods from the auto-generated class need to be automatically injected into the manual layer through the `@_gapic.add_methods` decorator. It's not surprising that such dynamic magic confuses the static linter. It's also not something that can be easily fixed in the library itself.

Of course littering the source with numerous `# pylint: disable=no-member` comments is not appealing, but fortunately `pylint` can be [configured](http://pylint.pycqa.org/en/latest/whatsnew/1.6.html#new-features) to ignore that with the `--generated-members` setting. If you can stick to a common name for subscriber instances in your app, writing a regex that matches method invocations on them should do the trick.

Would that be feasible for your case?

**Comment by nicpreuss** [comment]
@anguillanneuf just ran into the same issue and found out this thread....I was wondering if there is any update on a release of the v2 allowing the fix to work with pylint?

**Comment by anguillanneuf** [comment]
@nicpreuss On v2 there isn't. But thank you for raising it so it stays on our radar.

**Comment by g2github** [comment]
I'm having this same issue, but am not clear what the "fix" is.  How do I get past this error?

**Comment by nicpreuss** [comment]
@g2github hey probably not a best practice but here is how I hacked this 
topic_path = publisher.topic_path(project_id, topic_id)# pylint: disable=no-member

the pylint: disable=no-member allows you to override the error.

**Comment by g2github** [comment]
thanks @nicpreuss

**Comment by nicpreuss** [comment]
let me know if it works for you or if you find a better solution @g2github

**Comment by g2github** [comment]
looks like i need # pylint: disable=no-member all over my code... how can this be possible?

**Comment by dinvlad** [comment]
Any updates here?

**Comment by plamut** [comment]
@dinvlad About the ways to fix the error or the v2 client?

AFAIK v2 client cannot be expected yet in the near/mid future, while IMHO the best way to silence false pylint errors is by leveraging the `generated-members` setting - better than littering the code with `pylint: disable=no-member`, unless there are only a few occurrences.

**Comment by dinvlad** [comment]
Thanks, that would be much appreciated!

**Comment by plamut** [comment]
Update: The V2 client is currently still in the planning phase, and the earliest implementation is not expected before Q3/2021 (best case scenario).

**Comment by MiltiadisKoutsokeras** [comment]
Hi all, 

In case someone is reading this, the problem with pylint still persists using google-cloud-pubsub==2.9.0.

**Comment by plamut** [comment]
@MiltiadisKoutsokeras Would you also mind to check with the tip of the `main` branch? (not released yet)

Recently, a considerable [refactoring](https://github.com/googleapis/python-pubsub/pull/552) of the clients was merged - the hand-written classes now directly inherit from the generated classes, instead of dynamically injecting the generated methods into their namespace (static type checkers couldn't actually know that).

Simplifying the code should not confuse static type checkers anymore.

**Comment by adamwojt** [comment]
Same with pyright here with `google-cloud-pubsub==2.8.0`.
![image](https://user-images.githubusercontent.com/45100954/163556982-39186f20-24d8-4d84-9688-4e035849ea80.png)

**Comment by iamtodor** [comment]
@adamwojt in your case it's because of `topic_path()` is` @staticmethod`

```python
    @staticmethod
    def topic_path(
        project: str,
        topic: str,
    ) -> str:
        """Returns a fully-qualified topic string."""
        return "projects/{project}/topics/{topic}".format(
            project=project,
            topic=topic,
        )
```

But treating it as static also does not work properly:

```python
topic_path = pubsub_v1.PublisherClient.topic_path(PROJECT_ID, "blah")
```
