### ISSUE TITLE
Ack deadline not respected?

### ISSUE THREAD

**Issue by adamwojt** [googleapis/python-pubsub#676]
With Ack deadline set to 10 sec on subscription and below code I am getting batch of messages (for testing there is only 5 in queue) but then pulling stops. Is this expected behavior? Shouldn't messages come back again after 10 sec has passed? I know there is no reason to not `ack` / `nack` but this seems like a bit weird behavior for me. 

``` python
from google.cloud import pubsub_v1

def callback(m):
    m = m.data.decode('utf-8')
    print(m)

with pubsub_v1.SubscriberClient() as s:
    f = s.subscribe("projects/test-dev-338714/subscriptions/adam_test-sub", callback=callback)
    f.result()
```

**Comment by hongalex** [comment]
The subscription's ack deadline is not used by the client library. Because our client libraries provide automatic lease management, we will continue to extension the expiration time by calling `ModifyAckDeadline` under the hood, limited by [`max_lease_duration`](https://github.com/googleapis/python-pubsub/blob/5eee19ee3db0c779d87d840a94e348cbc246eab0/google/cloud/pubsub_v1/types.py#L159).
