### ISSUE TITLE
502 bad gateway error logging / reporting

### ISSUE THREAD

**Issue by kc-sn** [googleapis/python-pubsub#827]
I've had a support ticket open with GCP support since September tracking this issue. We are receiving between 100-1000+ daily reports of `502 bad gateway` via Datadog APM while utilizing pubsub at production volumes (200+ messages/sec at peak). (see https://github.com/DataDog/dd-trace-py/issues/4588 for details).

Thus far, GCP support has not been able to correlate these errors with anything on their backend, and that's hard to believe given that we can see our ack delays go up any time there are transient issues reported by DD APM.

Is there any additional logging or debugging options available to gather more information from the GRPC unary call? We tried turning on full debug logs but within 10 minutes we'd produced nearly a TB of logs (this is expensive). (see https://github.com/googleapis/python-pubsub/issues/752#issuecomment-1302608914)

Any additional assistance would be greatly appreciated, we are at the point now where we're beginning to consider service alternatives.

**Comment by acocuzzo** [comment]
@kc-sn 502 as you likely are aware, bad gateway errors are unrelated to the Pub/Sub library or the Pub/Sub backend.  

On GKE specifically, we have seen these errors associated with CPU spikes, so that may be an avenue of investigation, but this should be investigated in another forum.

Regarding logging cost, you may be able to filter your logs to reduce cost.

As for mitigating for ack delays, you may want to consider subscriber flow control to restrict the number of messages per client, and increasing your clients. If you are concerned about ack delays and want to consult with pub sub for suggestions, I would recommend opening a support ticket so the team can look at your subscription specifically and advise based on your ack expiration rate and streaming pull utilization.
